### ISSUE TITLE
Compiler code

### ISSUE THREAD

**Issue by kybio** [akadjoker/H3DView#1]
Where are the TJvLinkLabel class to build in RAD Studio XE4. Its design is very interesting, congratulations!

**Comment by akadjoker** [comment]
kybio jvcl.delphi-jedi.org/ but you can remove all jvcl units

**Comment by kybio** [comment]
Thank you!!!

**Comment by akadjoker** [comment]
No prob ;)

**Comment by kybio** [comment]
Hi akadjoker, I'm trying to load the COLLADA format with your application, but the skeleton is detached from the mesh, while the mesh is in the T position, the skeleton is in the initial form of the animation. I'm importing a model from MIXAMO.

![screen](https://user-images.githubusercontent.com/10429458/103974684-15826500-5151-11eb-94fe-68faef0ac3e3.jpg)
